version: '3.8'
services:
  backend:
    image: python:3.9-slim
    working_dir: /app
    volumes:
      - ./crewai_be:/app
    ports:
      - '5000:5000'
    command: python api.py

  frontend:
    image: node:14
    working_dir: /app
    volumes:
      - ./nextjs_app:/app
    ports:
      - '3000:3000'
    depends_on:
      - backend
    command: |
      sh -c "npm install && npm run dev"
